import 'package:flutter/material.dart';

import 'package:jezail_ui/presentation/tabs/device/widgets/device_formatters.dart';

final List<CardConfig> deviceCardConfigs = [
  CardConfig('Device', Icons.smartphone, 'device', (data) => {
    'Name': data['deviceName'],
    'Model': data['model'],
    'Manufacturer': data['manufacturer'],
    'Android Version': data['androidVersion'],
    'SDK Level': data['sdkInt'],
    'Security Patch': data['securityPatch'],
    'Root Access': (data['isRooted'] ?? false) ? 'Yes' : 'No',
    'Debuggable': (data['isDebuggable'] ?? false) ? 'Yes' : 'No',
    'Fingerprint': data['fingerprint'],
  }),
  CardConfig('Build', Icons.construction, 'build', (data) => {
    'Brand': data['brand'],
    'Device': data['device'],
    'Product': data['product'],
    'Hardware': data['hardware'],
    'Build ID': data['buildId'],
    'Build Type': data['buildType'],
    'Build Tags': data['buildTags'],
    'Bootloader': data['bootloader'],
    'Radio': data['radio'],
    'Board': data['board'],
    'Build Time': data['time'] != null
      ? DateTime.fromMillisecondsSinceEpoch(data['time']).toString()
      : null,
  }),
  CardConfig('Battery', Icons.battery_std, 'battery', (data) => {
    'Level': '${data['level'] ?? 0}%',
    'Status': getBatteryStatus(data['status']),
    'Health': getBatteryHealth(data['health']),
    'Temperature': '${((data['temperature'] ?? 0) / 10).toStringAsFixed(1)}°C',
    'Voltage': '${data['voltage'] ?? 0}mV',
    'Technology': data['technology'],
    'Present': (data['present'] ?? false) ? 'Yes' : 'No',
    'Plugged': (data['plugged'] ?? false) ? 'Yes' : 'No',
    'Scale': data['scale']?.toString(),
    'Plugged Type': getBatteryPluggedType(data['pluggedTypes']),
  }),
  CardConfig('Processor', Icons.developer_board, 'cpu', (data) => {
    'Architecture': data['architecture'],
    'Cores': data['cores']?.toString(),
    'Processor': data['processor'],
    'Max Frequency': '${data['maxFreq']} GHz',
    '64-bit Support': (data['is64Bit'] ?? false) ? 'Yes' : 'No',
    'Supported ABIs': (data['supportedAbis'] as List?)?.join(', '),
    'Features Count': (data['features'] as List?)?.length.toString(),
    'CPU Features': (data['features'] as List?)?.join(', '),
  }),
  CardConfig('Memory', Icons.memory, 'memory', (data) => {
    'Total RAM': formatBytes(data['totalMem']),
    'Available RAM': formatBytes(data['availMem']),
    'Used RAM': formatBytes(data['usedMem']),
    'Memory Total': formatBytes(data['memTotal']),
    'Memory Free': formatBytes(data['memFree']),
    'Memory Available': formatBytes(data['memAvailable']),
    'Cached': formatBytes(data['cached']),
    'Buffers': formatBytes(data['buffers']),
    'Swap Total': formatBytes(data['swapTotal']),
    'Swap Free': formatBytes(data['swapFree']),
    'Low Memory': (data['lowMemory'] ?? false) ? 'Yes' : 'No',
    'Low RAM Device': (data['isLowRamDevice'] ?? false) ? 'Yes' : 'No',
    'Shared Memory': formatBytes(data['shmem']),
    'Low Memory Threshold': formatBytes(data['threshold']),
  }),
  CardConfig('Storage', Icons.folder, 'storageDetails', (data) => {
    'Internal Total': formatBytes(data['internal']?['totalSpace']),
    'Internal Free': formatBytes(data['internal']?['freeSpace']),
    'Internal Used': formatBytes(data['internal']?['usedSpace']),
    'Internal Usable': formatBytes(data['internal']?['usableSpace']),
    'Internal Path': data['internal']?['path'],
    'External Total': formatBytes(data['external']?['totalSpace']),
    'External Free': formatBytes(data['external']?['freeSpace']),
    'External Path': data['external']?['path'],
    'Root Total': formatBytes(data['root']?['totalSpace']),
    'Root Path': data['root']?['path'],
    'System Total': formatBytes(data['system']?['totalSpace']),
    'System Path': data['system']?['path'],
    'Data Total': formatBytes(data['data']?['totalSpace']),
    'Data Free': formatBytes(data['data']?['freeSpace']),
    'Data Path': data['data']?['path'],
    'Cache Total': formatBytes(data['cache']?['totalSpace']),
    'Cache Path': data['cache']?['path'],
    'Mount Points': data['mountPoints']?.length?.toString() ?? '0',
  }),
  CardConfig('Network', Icons.wifi, 'network', (data) => {
    'Has Internet': (data['activeConnection']?['hasInternet'] ?? false) ? 'Yes' : 'No',
    'WiFi Connected': (data['activeConnection']?['hasWifi'] ?? false) ? 'Yes' : 'No',
    'Cellular Connected': (data['activeConnection']?['hasCellular'] ?? false) ? 'Yes' : 'No',
    'Ethernet Connected': (data['activeConnection']?['hasEthernet'] ?? false) ? 'Yes' : 'No',
    'Network Validated': (data['activeConnection']?['validated'] ?? false) ? 'Yes' : 'No',
    'WiFi SSID': data['wifi']?['ssid'],
    'IP Address': data['wifi']?['ipAddress'],
    'RSSI': data['wifi']?['rssi'] != null ? '${data['wifi']['rssi']} dBm' : null,
    'Link Speed': data['wifi']?['linkSpeed'] != null ? '${data['wifi']['linkSpeed']} Mbps' : null,
    'Frequency': data['wifi']?['frequency'] != null ? '${data['wifi']['frequency']} MHz' : null,
    'Network ID': data['wifi']?['networkId']?.toString(),
    'TX Link Speed': data['wifi']?['txLinkSpeed'] != null ? '${data['wifi']['txLinkSpeed']} Mbps' : null,
    'RX Link Speed': data['wifi']?['rxLinkSpeed'] != null ? '${data['wifi']['rxLinkSpeed']} Mbps' : null,
  }),
  CardConfig('Cellular', Icons.signal_cellular_4_bar, 'network', (data) => {
    'Network Operator': data['cellular']?['networkOperator'],
    'Network Type': data['cellular']?['networkType']?.toString(),
    'Phone Type': data['cellular']?['phoneType']?.toString(),
    'SIM State': data['cellular']?['simState']?.toString(),
    'Roaming': (data['cellular']?['isNetworkRoaming'] ?? false) ? 'Yes' : 'No',
    'Data Enabled': (data['cellular']?['isDataEnabled'] ?? false) ? 'Yes' : 'No',
  }),
  CardConfig('Network DHCP', Icons.router, 'network', (data) => {
    'DHCP IP': data['dhcp']?['ipAddress'],
    'Gateway': data['dhcp']?['gateway'],
    'MTU': data['dhcp']?['mtu']?.toString(),
    'DHCP DNS': (data['dhcp']?['dnsServers'] as List?)?.join(', '),
  }),
  CardConfig('Network Interface', Icons.settings_ethernet, 'network', (data) => {
    'Interface Name': data['linkProperties']?['interfaceName'],
    'Link Addresses': (data['linkProperties']?['linkAddresses'] as List?)?.join('\n'),
    'Interface DNS': (data['linkProperties']?['dnsServers'] as List?)?.join(', '),
    'Routes Count': (data['linkProperties']?['routes'] as List?)?.length.toString(),
    'Network Interfaces': (data['interfaces'] as List?)?.length.toString(),
  }),
  CardConfig('Security', Icons.shield, 'security', (data) => {
    'SELinux Status': data['status']?.toString() ?? 'Unknown',
  }),
  CardConfig('Environment', Icons.terminal, 'env', (data) => Map.fromEntries(
    data.entries.where((e) => e.key != '_').map((e) => MapEntry(e.key, e.value)),
  )),
  CardConfig('System Properties', Icons.settings_applications, 'properties', (data) => {
    'Build User': data['ro.build.user'],
    'Build Host': data['ro.build.host'],
    'Kernel Version': data['ro.kernel.version'],
    'Init RC': data['ro.build.version.incremental'],
    'Display ID': data['ro.build.display.id'],
    'Secure': data['ro.secure'],
    'Debuggable System': data['ro.debuggable'],
    'ADB Enabled': data['ro.adb.secure'],
    'Zygote': data['ro.zygote'],
    'Dalvik Heap Size': data['dalvik.vm.heapsize'],
    'OpenGL Version': data['ro.opengles.version'],
    'WiFi Direct': data['wifi.direct.interface'],
    'Total Properties': data.length.toString(),
  }),
];
